### ISSUE TITLE
segmentation fault when comput gradient of the image pyramid on Kitti dataset

### ISSUE THREAD

**Issue by Ning-Yin** [jzubizarreta/dsm#23]
Hi, thanks for your great project! Have you run this project on Kitti dataset? I tried but segmentation fault happened.

> Thread 13 "EurocExample" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fffb2b53700 (LWP 30677)]
> 0x00007ffff76c3b78 in dsm::Frame::gradient(int) const ()
>    from /home/yin/dsm_ws/dsm/build/lib/libdsm.so
> (gdb) bt
> #0  0x00007ffff76c3b78 in dsm::Frame::gradient(int) const () at /home/yin/dsm_ws/dsm/build/lib/libdsm.so
> #1  0x00007ffff76fb302 in dsm::PointDetector::detect(std::shared_ptr<dsm::Frame> const&, int, int*, dsm::IVisualizer*) () at /home/yin/dsm_ws/dsm/build/lib/libdsm.so
> #2  0x00007ffff7704efe in dsm::FullSystem::createCandidates(std::shared_ptr<dsm::Frame> const&) ()
>     at /home/yin/dsm_ws/dsm/build/lib/libdsm.so
> #3  0x00007ffff770dd94 in dsm::FullSystem::initialize(std::shared_ptr<dsm::Frame> const&) ()
>     at /home/yin/dsm_ws/dsm/build/lib/libdsm.so
> #4  0x00007ffff770e12e in dsm::FullSystem::trackFrame(int, double, unsigned char*) ()

It seemed that error happened when calculate gradient of image pyramid. Do you have suggestions about it? Thanks a lot!

**Comment by zeroAska** [comment]
Are you able to get it work on Kitti?
